sudo: false
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test
  - npm run test:coverage

after_success:
  - npm run test:coveralls
