sudo: false
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn run lint
  - yarn run build
  - yarn run test
  - yarn run test:coverage

after_success:
  - yarn run test:coveralls
