version: '3.7'

services:
  fbg:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      SERVER_TYPE: 'FBG'
  bgio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      SERVER_TYPE: 'BGIO'