mongo:
  image: mongo
  cpu_shares: 100
  mem_limit: 262144000
  volumes:
    - mongoTurnatoData:/data/db
web:
  image: turnato
  command: npm start
  cpu_shares: 100
  mem_limit: 262144000
  ports:
    - "80:3000"
  links:
    - mongo
